"""EN: Domain layer package exports for AI ethics evaluation engine. | ES: Exportaciones del paquete de la capa de dominio para el motor de evaluacion de etica en IA."""

from domain.entities import (
    CaseStudy,
    ComplianceStatus,
    DecisionImpactResult,
    DecisionOption,
    DimensionScore,
    EthicalAssessment,
    EthicalDimension,
    EthicalFinding,
    EvaluationMetric,
    FrameworkAssessment,
    FrameworkType,
    LinguisticArtifact,
    MultidimensionalMatrix,
    RiskTier,
    Scenario,
    TaskType,
    UserDecision,
)
from domain.exceptions import (
    CaseStudyNotFoundError,
    DomainError,
    InvalidDecisionOptionError,
    InvalidMetricValueError,
    ScenarioNotFoundError,
    UnsupportedFrameworkError,
)
from domain.interfaces import (
    IAssessmentRepository,
    ICaseStudyRepository,
    IDecisionImpactRepository,
    IEthicalEvaluator,
    IScenarioRepository,
)

__all__ = [
    "CaseStudy",
    "CaseStudyNotFoundError",
    "ComplianceStatus",
    "DecisionImpactResult",
    "DecisionOption",
    "DimensionScore",
    "DomainError",
    "EthicalAssessment",
    "EthicalDimension",
    "EthicalFinding",
    "EvaluationMetric",
    "FrameworkAssessment",
    "FrameworkType",
    "IAssessmentRepository",
    "ICaseStudyRepository",
    "IDecisionImpactRepository",
    "IEthicalEvaluator",
    "IScenarioRepository",
    "InvalidDecisionOptionError",
    "InvalidMetricValueError",
    "LinguisticArtifact",
    "MultidimensionalMatrix",
    "RiskTier",
    "Scenario",
    "ScenarioNotFoundError",
    "TaskType",
    "UnsupportedFrameworkError",
    "UserDecision",
]
